name: Js Lint

on:
  push:
    branches:
      - master
    paths:
      - '**.ts'
      - '**.js'

  pull_request:
    branches:
      - master
    paths:
      - '**.ts'
      - '**.js'

jobs:
  js-lint:
    name: Prettier check
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./dex/tests/permissioned
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable corepack
        run: corepack enable
        shell: bash

      - name: Install yarn
        run: yarn
        
      - name: Run prettier
        run: yarn prettier '*/**/*{.js,.ts}' --check