name: Lint & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: fmt & clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache binaries
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            dex/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
  
  test:
    name: Build & test
    runs-on: ubuntu-latest
    needs: ['lint']
    strategy:
      fail-fast: false
      matrix:
        path: ['Cargo.toml',
               'dex/Cargo.toml',
               'dex/fuzz/Cargo.toml']
    env:
      PROGRAM_PATH: ${{ matrix.path }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache binaries
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            dex/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Test build
        run: |
          cargo build --manifest-path ${{ matrix.path }} --release

      - name: Unit tests
        run: |
          cargo test --manifest-path ${{ matrix.path }} --workspace